In [84]:
import pandas as pd
import statistics

In [85]:
df1 = pd.read_csv('../dylancastillo/books.csv')
df1['isbn'] = df1['isbn10']
print(len(df1))
df1.head(3)

6810

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,isbn
0,9780002005883,0002005883,Gilead,NaN,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,0002005883
1,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,0002261987
2,9780006163831,0006163831,The One Tree,NaN,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982.0,3.97,479.0,172.0,0006163831

In [86]:
df2 = pd.read_csv('books.csv', index_col=0)
print(len(df2))
df2.head(3)

11127

,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
bookID,,,,,,,,,,,
1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic

In [87]:
# Merged Data Sets
df = pd.merge(df1, df2, on='isbn', how='inner')
df

,isbn13_x,isbn10,title_x,subtitle,authors_x,categories,thumbnail,description,published_year,average_rating_x,...,title_y,authors_y,average_rating_y,isbn13_y,language_code,num_pages_y,ratings_count_y,text_reviews_count,publication_date,publisher
0,9780006163831,0006163831,The One Tree,NaN,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982.0,3.97,...,The One Tree (The Second Chronicles of Thomas ...,Stephen R. Donaldson,3.98,9780006163831,en-GB,479,174,3,11/18/1996,Fontana
1,9780006178736,0006178731,Rage of angels,NaN,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,...,Rage of Angels,Sidney Sheldon,3.93,9780006178736,eng,512,30283,860,8/3/1999,HarperCollins Publishers
2,9780006280897,0006280897,The Four Loves,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,...,The Four Loves,C.S. Lewis,4.14,9780006280897,en-US,170,34681,1084,6/5/2002,HarperCollins Publishers Ltd
3,9780006353287,0006353282,An Autobiography,NaN,Agatha Christie,"Authors, English",http://books.google.com/books/content?id=c49GQ...,Donation.,1977.0,4.27,...,Agatha Christie: An Autobiography,Agatha Christie/Robert Welch Herrick,4.27,9780006353287,eng,560,4296,310,1/2/2001,HarperCollins
4,9780006380832,0006380832,Empires of the Monsoon,A History of the Indian Ocean and Its Invaders,Richard Hall,"Africa, East",http://books.google.com/books/content?id=MuPEQ...,Until Vasco da Gama discovered the sea-route t...,1998.0,4.41,...,Empires of the Monsoon: A History of the India...,Richard Seymour Hall,4.39,9780006380832,eng,608,67,12,1/1/1998,HarperCollins Publishers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5681,9784770028969,4770028962,Coin Locker Babies,NaN,村上龍,Fiction,http://books.google.com/books/content?id=87DJw...,Rescued from the lockers in which they were le...,2002.0,3.75,...,Coin Locker Babies,Ryū Murakami/Stephen Snyder,3.68,9784770028969,eng,393,6440,298,8/9/2002,Kodansha
5682,9788172235222,8172235224,Mistaken Identity,NaN,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,...,Mistaken Identity,Nayantara Sahgal,2.98,9788172235222,eng,324,0,0,12/30/2016,Harper Collins
5683,9788445074879,8445074873,Fahrenheit 451,NaN,Ray Bradbury,Book burning,NaN,NaN,2004.0,3.98,...,Fahrenheit 451,Ray Bradbury,3.99,9788445074879,eng,186,5733,606,4/1/2004,Del Rey
5684,9789027712059,9027712050,The Berlin Phenomenology,NaN,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,...,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel/Michael John Petry,0.00,9789027712059,eng,210,0,0,5/31/1981,Springer
5685,9789042003408,9042003405,'I'm Telling You Stories',Jeanette Winterson and the Politics of Reading,Helena Grice;Tim Woods,Literary Criticism,http://books.google.com/books/content?id=2lVyR...,This is a jubilant and rewarding collection of...,1998.0,3.70,...,I'm Telling You Stories: Jeanette Winterson an...,Helena Grice/Tim Woods,3.70,9789042003408,eng,136,10,2,1/1/1998,Brill/Rodopi

In [88]:
# More data cleaning
def min_length(x, y):
    if len(str(x)) < len(str(y)):
        return x
    else:
        return y
    
df['title'] = df.apply(lambda x: min_length(x['title_x'], x['title_y']), axis=1)
df['authors'] = df.apply(lambda x: min_length(x['authors_x'], x['authors_y']), axis=1)
df['avg_rating'] = df.apply(lambda x: statistics.mean([x['average_rating_x'], x['average_rating_y']]), axis=1)
df['num_pages'] = df.apply(lambda x: statistics.mean([x['num_pages_x'], x['num_pages_y']]), axis=1)
df['num_ratings'] = df.apply(lambda x: statistics.mean([x['ratings_count_x'], x['ratings_count_y']]), axis=1)
subset = ['isbn10', 'title', 'subtitle', 'authors', 'categories', 'description', 'avg_rating', 'num_pages', 'num_ratings', 'publisher', 'publication_date']
df = df[subset]
df.sort_values(by = 'num_ratings', ascending=False, inplace=True)
df

C:\Users\sethj\AppData\Local\Temp\ipykernel_17560\1052958319.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.sort_values(by = 'num_ratings', ascending=False, inplace=True)

,isbn10,title,subtitle,authors,categories,description,avg_rating,num_pages,num_ratings,publisher,publication_date
1374,0316015849,Twilight,NaN,Stephenie Meyer,Young Adult Fiction,With 160 million copies of the Twilight Saga s...,3.590,499.5,4482503.5,Little Brown and Company,9/6/2006
3072,0618260307,The Hobbit or There and Back Again,NaN,J.R.R. Tolkien,Juvenile Fiction,A newly rejacketed edition of the classic tale...,4.265,366.0,2447931.0,Houghton Mifflin,8/15/2002
4915,1416524797,Angels & Demons,NaN,Dan Brown,Fiction,The explosive Robert Langdon thriller from Dan...,3.885,736.0,2349295.0,Pocket Books,4/1/2006
2239,043965548X,Harry Potter and the Prisoner of Azkaban (Book 3),NaN,"Rowling, J.K.",Juvenile Fiction,"For twelve long years, the dread fortress of A...",4.555,435.0,2244728.5,Scholastic Inc.,5/1/2004
2203,0439064864,Harry Potter and the Chamber of Secrets (Book 2),NaN,"Rowling, J.K.",Juvenile Fiction,"In Harry Potter and the Chamber of Secrets, th...",4.415,341.0,2204762.5,Arthur A. Levine Books / Scholastic Inc.,6/2/1999
...,...,...,...,...,...,...,...,...,...,...,...
3687,0744005612,Juiced,NaN,Doug Walsh,Games,BradyGames' Juiced Official Strategy Guide inc...,0.000,112.0,0.0,BradyGames,6/1/2005
1366,0313309337,The Fantastic Vampire,Studies in the Children of the Night : Selecte...,James Craig Holte,Literary Criticism,Wherever vampires existed in the imaginations ...,0.000,176.0,0.0,Greenwood Press,3/30/2002
3715,0747566828,Super Fast Out of Control,NaN,Louis Sachar,Children's stories,The seventh story in the series featuring all ...,3.750,128.0,0.0,Bloomsbury Publishing PLC,5/2/2005
3729,0750244917,Roald Dahl,The Storyteller,Jason Hook,"Novelists, English","Born in Wales in 1916 to Norwegian parents, Ro...",4.060,48.0,0.0,Hodder Wayland,8/12/2004
5570,189044717X,Open City 6,The Only Woman He's Ever Left,Thomas Beller;James Purdy;Strawberry Saroyan;D...,Fiction,The most important new literary journal to eme...,0.000,200.0,0.0,Grove Press Open City Books,10/13/2000

In [89]:
import re
def gen_title(x):
    if str(x['subtitle']) == 'nan' or x['subtitle'] == 'NaN' or x['subtitle'] == None:
        return x['title']
    else:
        return x['title'] + ' (' + str(x['subtitle']) + ')'
df['Title'] = df.apply(lambda x: gen_title(x), axis=1)
df['Author'] = df['authors']
df['Subjects'] = df['categories']
df['Subjects'] = df['Subjects'].apply(lambda x: re.sub(r'[^a-zA-Z0-9 ]', '', str(x)).strip())
df['ISBN'] = df['isbn10']
df['Publisher'] = df['publisher']
df['Publication Year'] = df['publication_date'].str[-4:]

C:\Users\sethj\AppData\Local\Temp\ipykernel_17560\3804602046.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Title'] = df.apply(lambda x: gen_title(x), axis=1)
C:\Users\sethj\AppData\Local\Temp\ipykernel_17560\3804602046.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Author'] = df['authors']
C:\Users\sethj\AppData\Local\Temp\ipykernel_17560\3804602046.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Subjects'] = df['categories']
C:\Users\sethj\AppData\Local\Temp\ipykernel_17560\3804602046.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Subjects'] = df['Subjects'].apply(lambda x: re.sub(r'[^a-zA-Z0-9 ]', '', str(x)).strip())
C:\Users\sethj\AppData\Local\Temp\ipykernel_17560\3804602046.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ISBN'] = df['isbn10']
C:\Users\sethj\AppData\Local\Temp\ipykernel_17560\3804602046.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Publisher'] = df['publisher']
C:\Users\sethj\AppData\Local\Temp\ipykernel_17560\3804602046.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Publication Year'] = df['publication_date'].str[-4:]

In [90]:
df = df[["ISBN","Title","Author","Publisher","Publication Year",'Subjects']]
df

,ISBN,Title,Author,Publisher,Publication Year,Subjects
1374,0316015849,Twilight,Stephenie Meyer,Little Brown and Company,2006,Young Adult Fiction
3072,0618260307,The Hobbit or There and Back Again,J.R.R. Tolkien,Houghton Mifflin,2002,Juvenile Fiction
4915,1416524797,Angels & Demons,Dan Brown,Pocket Books,2006,Fiction
2239,043965548X,Harry Potter and the Prisoner of Azkaban (Book 3),"Rowling, J.K.",Scholastic Inc.,2004,Juvenile Fiction
2203,0439064864,Harry Potter and the Chamber of Secrets (Book 2),"Rowling, J.K.",Arthur A. Levine Books / Scholastic Inc.,1999,Juvenile Fiction
...,...,...,...,...,...,...
3687,0744005612,Juiced,Doug Walsh,BradyGames,2005,Games
1366,0313309337,The Fantastic Vampire (Studies in the Children...,James Craig Holte,Greenwood Press,2002,Literary Criticism
3715,0747566828,Super Fast Out of Control,Louis Sachar,Bloomsbury Publishing PLC,2005,Childrens stories
3729,0750244917,Roald Dahl (The Storyteller),Jason Hook,Hodder Wayland,2004,Novelists English
5570,189044717X,Open City 6 (The Only Woman He's Ever Left),Thomas Beller;James Purdy;Strawberry Saroyan;D...,Grove Press Open City Books,2000,Fiction

In [94]:
df.to_csv('../Exported/GRD_Sel.csv', index=False)

In [ ]:
df.Subjects.value_counts()

Subjects
Fiction                      2211
Juvenile Fiction              474
Biography ; Autobiography     354
History                       235
Literary Criticism            148
                             ...
English language                1
Physicists                      1
Ballet dancers                  1
Country life                    1
Paris (France)                  1
Name: count, Length: 405, dtype: int64